### ISSUE TITLE
Game patching do not work if starts from NAND

### ISSUE THREAD

**Issue by re2cc** [leoetlino/Luma3DS#2]
**System model:**

New 2DS

**SysNAND version (+emu/redNAND version if applicable):**

11.10.0-43U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

FastBoot3ds (It is B9S?)

**Luma3DS version:**

10.0.1.bs5

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off)

Splash duration: (3 seconds)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Today I install FastBoot3ds, and I configure it to boot by default with the boot.firm in the NAND (I replace boot.firm of the NAND with this version too), but when I try to play Majora´s Mask, the game patch don´t work.
I do not am sure if this works before I install FastBoot.

**Steps to reproduce:**

1. Start boot.firm from NAND.

2. Try to run Majora's Mask with Project Restoration

**Comment by leoetlino** [comment]
Sorry, I missed your message. What do you mean by "doesn't work"? Do you get any particular error?

**Comment by re2cc** [comment]
Thanks for answer; No, the game does not use the patch, It start without the sound that creates the patch and the other features.

**Comment by leoetlino** [comment]
And you're using a BPS patch (code.bps), right? Since Luma doesn't have BPS patching support (yet!) that must mean your console is somehow still using the old boot.firm rather than my boot.firm. Could you please double check both the boot.firm that is on your NAND and the boot.firm on the SD card are indeed my boot.firm?

**Comment by re2cc** [comment]
I chek it, This is strange, actualy I am on Majora´s Mask v1.1, but I use the .ips patch (I can confirm that it works with your Luma if it run in SD). Anyway, I am very sure than I am using your Luma and is on the NAND (IMAGE).
![LUMA3DSBPS](https://user-images.githubusercontent.com/42478705/67443644-39e53680-f5cb-11e9-9fb1-676bac1b8f7e.jpg)

**Comment by leoetlino** [comment]
I'm sorry, but I have no idea why game patching would be disabled and only when starting from NAND... Is starting Luma from the SD card an option for you?

**Comment by re2cc** [comment]
Yes, I can use it, but I like to use Luma from the NAND, anyway, thanks for answering and following up.
